export const TYPE_COLORS = {
  NORMAL: "#aaaa99",
  FIRE: "#ff4422",
  WATER: "#3399ff",
  ELECTRIC: "#ffcc33",
  GRASS: "#77cc55",
  ICE: "#66ccff",
  FIGHTING: "#bb5544",
  POISON: "#aa5599",
  GROUND: "#ddbb55",
  FLYING: "#8899ff",
  PSYCHIC: "#ff5599",
  BUG: "#aabb22",
  ROCK: "#bbaa66",
  GHOST: "#6666bb",
  DRAGON: "#7766ee",
  DARK: "#775544",
  STEEL: "#aaaabb",
  FAIRY: "#ee99ee",
};

export const LEVEL_UP_MOVES = [
  {
    primary: "01",
    move: "Growl",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "100",
  },
  {
    primary: "01",
    move: "Scratch",
    type: ["Normal"],
    category: "Physical",
    pwr: "40",
    acc: "100",
  },
  {
    primary: "04",
    move: "Ember",
    type: ["Fire"],
    category: "Special",
    pwr: "40",
    acc: "100",
  },
  {
    primary: "08",
    move: "Quick Attack",
    type: ["Normal"],
    category: "Physical",
    pwr: "40",
    acc: "100",
  },
  {
    primary: "12",
    move: "Charm",
    type: ["Fairy"],
    category: "Status",
    pwr: "—",
    acc: "100",
  },
  {
    primary: "16",
    move: "Lick",
    type: ["Ghost"],
    category: "Physical",
    pwr: "30",
    acc: "100",
  },
  {
    primary: "20",
    move: "Fury Swipes",
    type: ["Normal"],
    category: "Physical",
    pwr: "18",
    acc: "80",
  },
  {
    primary: "24",
    move: "Psybeam",
    type: ["Psychic"],
    category: "Special",
    pwr: "65",
    acc: "100",
  },
  {
    primary: "28",
    move: "Bite",
    type: ["Dark"],
    category: "Physical",
    pwr: "60",
    acc: "100",
  },
  {
    primary: "32",
    move: "Sing",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "100",
  },
  {
    primary: "36",
    move: "Submission",
    type: ["Fighting"],
    category: "Physical",
    pwr: "80",
    acc: "80",
  },
  {
    primary: "40",
    move: "Fake Out",
    type: ["Normal"],
    category: "Physical",
    pwr: "40",
    acc: "100",
  },
  {
    primary: "44",
    move: "Slack Off",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "48",
    move: "Yawn",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "52",
    move: "Mystical Fire",
    type: ["Fire"],
    category: "Special",
    pwr: "75",
    acc: "100",
  },
  {
    primary: "56",
    move: "Discharge",
    type: ["Electric"],
    category: "Special",
    pwr: "80",
    acc: "100",
  },
  {
    primary: "60",
    move: "Torch Song",
    type: ["Fire"],
    category: "Special",
    pwr: "80",
    acc: "100",
  },
];

export const TM_MOVES = [
  {
    primary: "002",
    move: "Charm",
    type: ["Fairy"],
    category: "Status",
    pwr: "—",
    acc: "100",
  },
  {
    primary: "007",
    move: "Protect",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "016",
    move: "Psybeam",
    type: ["Psychic"],
    category: "Special",
    pwr: "65",
    acc: "100",
  },
  {
    primary: "019",
    move: "Disarming Voice",
    type: ["Fairy"],
    category: "Special",
    pwr: "40",
    acc: "100",
  },
  {
    primary: "024",
    move: "Fire Spin",
    type: ["Fire"],
    category: "Special",
    pwr: "35",
    acc: "85",
  },
  {
    primary: "025",
    move: "Facade",
    type: ["Normal"],
    category: "Physical",
    pwr: "70",
    acc: "100",
  },
  {
    primary: "041",
    move: "Stored Power",
    type: ["Psychic"],
    category: "Special",
    pwr: "20",
    acc: "100",
  },
  {
    primary: "047",
    move: "Endure",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "049",
    move: "Sunny Day",
    type: ["Fire"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "050",
    move: "Rain Dance",
    type: ["Water"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "054",
    move: "Psyshock",
    type: ["Psychic"],
    category: "Special",
    pwr: "80",
    acc: "100",
  },
  {
    primary: "059",
    move: "Zen Headbutt",
    type: ["Psychic"],
    category: "Physical",
    pwr: "80",
    acc: "90",
  },
  {
    primary: "070",
    move: "Sleep Talk",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "075",
    move: "Light Screen",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "079",
    move: "Dazzling Gleam",
    type: ["Fairy"],
    category: "Special",
    pwr: "80",
    acc: "100",
  },
  {
    primary: "080",
    move: "Metronome",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "085",
    move: "Rest",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "103",
    move: "Substitute",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "109",
    move: "Trick",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "100",
  },
  {
    primary: "117",
    move: "Hyper Voice",
    type: ["Normal"],
    category: "Special",
    pwr: "90",
    acc: "100",
  },
  {
    primary: "120",
    move: "Psychic",
    type: ["Psychic"],
    category: "Special",
    pwr: "90",
    acc: "100",
  },
  {
    primary: "122",
    move: "Encore",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "100",
  },
  {
    primary: "128",
    move: "Amnesia",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "129",
    move: "Calm Mind",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "130",
    move: "Helping Hand",
    type: ["Normal"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "138",
    move: "Psychic Terrain",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "140",
    move: "Nasty Plot",
    type: ["Dark"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "157",
    move: "Overheat",
    type: ["Fire"],
    category: "Special",
    pwr: "130",
    acc: "90",
  },
  {
    primary: "161",
    move: "Trick Room",
    type: ["Psychic"],
    category: "Status",
    pwr: "—",
    acc: "—",
  },
  {
    primary: "163",
    move: "Hyper Beam",
    type: ["Normal"],
    category: "Special",
    pwr: "150",
    acc: "90",
  },
  {
    primary: "171",
    move: "Tera Blast",
    type: ["Normal"],
    category: "Special",
    pwr: "80",
    acc: "100",
  },
  {
    primary: "195",
    move: "Burning Jealousy",
    type: ["Fire"],
    category: "Special",
    pwr: "70",
    acc: "100",
  },
  {
    primary: "207",
    move: "Temper Flare",
    type: ["Fire"],
    category: "Physical",
    pwr: "75",
    acc: "100",
  },
  {
    primary: "217",
    move: "Future Sight",
    type: ["Psychic"],
    category: "Special",
    pwr: "120",
    acc: "100",
  },
  {
    primary: "227",
    move: "Alluring Voice",
    type: ["Fairy"],
    category: "Special",
    pwr: "80",
    acc: "100",
  },
];

export const EVOLUTION_MOVES = [
  {
    primary: "Jennova",
    move: "Heartflare Pulse",
    type: ["Psychic"],
    category: "Special",
    pwr: "90",
    acc: "100",
  },
];
